name: Deploy PHP and Vue.js to Hostinger

on:
  push:
    branches:
      - main  # Cambia esto por la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (para Vue.js)
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Asegúrate de usar una versión compatible de Node.js

    - name: Clean npm cache and install dependencies
      run: |
        rm -rf node_modules package-lock.json  # Elimina node_modules y package-lock.json
        npm install  # O usa 'npm ci' si tienes un archivo package-lock.json

    - name: Build Vue.js app
      run: |
        npm run build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # For debugging purposes
    - name: Confirm build output
      run: |
        echo "Listing contents of dist:"
        ls -la ./dist

    - name: Upload Vue.js files to Hostinger
      env:
        DEST_FOLDER: ~/domains/avaldez0.com/public_html/Collabtales/
      run: |
        ssh -o StrictHostKeyChecking=no -p 65002 u418653278@46.202.198.126 "mkdir -p $DEST_FOLDER"
        rsync -avz --delete -e "ssh -p 65002" --exclude '.git' ./dist/ u418653278@46.202.198.126:$DEST_FOLDER/
