name: Deploy PHP and Vue.js to Hostinger

on:
  push:
    branches:
      - main  # Cambia esto por la rama que uses para producción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js (para Vue.js)
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Asegúrate de usar una versión compatible de Node.js

    - name: Install dependencies (Vue.js)
      run: |
        npm install

    - name: Apply crypto polyfill (para resolver problemas de 'crypto')
      run: |
        echo "globalThis.crypto = require('crypto');" > ./node_modules/vite/dist/node/chunks/dep-CfG9u7Cn.js

    - name: Build Vue.js app
      run: |
        npm run build  # Generará los archivos estáticos en la carpeta 'dist'

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Upload PHP files to Hostinger
      run: |
        ssh -o StrictHostKeyChecking=no -p 65002 u418653278@46.202.198.126 "mkdir -p ~/public_html/colabtales/backend"
        rsync -avz -e "ssh -p 65002" --exclude '.git' ./backend/ u418653278@46.202.198.126:~/public_html/colabtales/backend/

    - name: Upload Vue.js files to Hostinger
      run: |
        ssh -o StrictHostKeyChecking=no -p 65002 u418653278@46.202.198.126 "mkdir -p ~/public_html/colabtales/frontend"
        rsync -avz -e "ssh -p 65002" --exclude '.git' ./frontend/dist/ u418653278@46.202.198.126:~/public_html/colabtales/frontend/

    - name: Install PHP dependencies (si las tienes)
      run: |
        ssh -p 65002 u418653278@46.202.198.126 << 'EOF'
          cd ~/public_html/colabtales/backend
          composer install --no-dev --optimize-autoloader
        EOF

    - name: Set file permissions
      run: |
        ssh -p 65002 u418653278@46.202.198.126 << 'EOF'
          cd ~/public_html/colabtales
          sudo chown -R u418653278:u418653278 ~/public_html/colabtales
          sudo chmod -R 755 ~/public_html/colabtales
        EOF
